In [15]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [16]:
df = sns.load_dataset('iris')
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [17]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [18]:
from sklearn.model_selection import train_test_split
X = df.drop('species', axis=1)
y = df['species']

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [20]:
from sklearn.neighbors import KNeighborsClassifier

In [33]:
model_knn = KNeighborsClassifier(n_neighbors=10)

In [34]:
model_knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=10)

In [35]:
model_knn.score(X_test, y_test)

0.98

In [24]:
from sklearn.svm import SVC

In [38]:
model_svm = SVC(gamma='auto')

In [39]:
model_svm.fit(X_train, y_train)

SVC(gamma='auto')

In [40]:
model_svm.score(X_test, y_test)

1.0

Grid search CV

In [37]:
from sklearn.model_selection import GridSearchCV

In [41]:
classifiers = GridSearchCV(estimator=model_svm, param_grid={'C': [0.1, 1, 10, 20, 30], 'kernel': ['rbf', 'linear'], 'gamma': ['scale', 'auto']}, cv=5, return_train_score=False)

In [42]:
classifiers.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [0.1, 1, 10, 20, 30], 'gamma': ['scale', 'auto'],
                         'kernel': ['rbf', 'linear']})

In [44]:
classifiers.cv_results_

{'mean_fit_time': array([0.0060708 , 0.00396481, 0.01204319, 0.00499396, 0.00512137,
        0.00501904, 0.00461774, 0.00291266, 0.00303946, 0.00371823,
        0.00527248, 0.00366592, 0.00322475, 0.00262833, 0.00283546,
        0.00257621, 0.00246229, 0.00254922, 0.00353594, 0.0025466 ]),
 'std_fit_time': array([0.00123568, 0.00078374, 0.01224546, 0.00079294, 0.00084518,
        0.00129938, 0.00146678, 0.00050477, 0.00071018, 0.00043429,
        0.00184168, 0.00102098, 0.0008185 , 0.00057546, 0.00078378,
        0.000825  , 0.00043574, 0.00054407, 0.00038068, 0.00086455]),
 'mean_score_time': array([0.00399895, 0.00387511, 0.00523958, 0.00450764, 0.0053237 ,
        0.00501547, 0.00345197, 0.00243382, 0.00208349, 0.00330081,
        0.00297146, 0.00281997, 0.00193744, 0.00251498, 0.00231662,
        0.0017189 , 0.0017715 , 0.00189419, 0.00260749, 0.00177221]),
 'std_score_time': array([0.0003832 , 0.00110008, 0.00157521, 0.00087364, 0.00213674,
        0.00305765, 0.00082242, 0.00069128, 0.00039829, 0.00127492,
        0.00085183, 0.00060725, 0.00037932, 0.00090508, 0.00076878,
        0.0003738 , 0.00028995, 0.00045154, 0.00059336, 0.00053598]),
 'param_C': masked_array(data=[0.1, 0.1, 0.1, 0.1, 1.0, 1.0, 1.0, 1.0, 10.0, 10.0,
                    10.0, 10.0, 20.0, 20.0, 20.0, 20.0, 30.0, 30.0, 30.0,
                    30.0],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value=1e+20),
 'param_gamma': masked_array(data=['scale', 'scale', 'auto', 'auto', 'scale', 'scale',
                    'auto', 'auto', 'scale', 'scale', 'auto', 'auto',
                    'scale', 'scale', 'auto', 'auto', 'scale', 'scale',
                    'auto', 'auto'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 0.1, 'gamma': 'scale', 'kernel': 'rbf'},
  {'C': 0.1, 'gamma': 'scale', 'kernel': 'linear'},
  {'C': 0.1, 'gamma': 'auto', 'kernel': 'rbf'},
  {'C': 0.1, 'gamma': 'auto', 'kernel': 'linear'},
  {'C': 1, 'gamma': 'scale', 'kernel': 'rbf'},
  {'C': 1, 'gamma': 'scale', 'kernel': 'linear'},
  {'C': 1, 'gamma': 'auto', 'kernel': 'rbf'},
  {'C': 1, 'gamma': 'auto', 'kernel': 'linear'},
  {'C': 10, 'gamma': 'scale', 'kernel': 'rbf'},
  {'C': 10, 'gamma': 'scale', 'kernel': 'linear'},
  {'C': 10, 'gamma': 'auto', 'kernel': 'rbf'},
  {'C': 10, 'gamma': 'auto', 'kernel': 'linear'},
  {'C': 20, 'gamma': 'scale', 'kernel': 'rbf'},
  {'C': 20, 'gamma': 'scale', 'kernel': 'linear'},
  {'C': 20, 'gamma': 'auto', 'kernel': 'rbf'},
  {'C': 20, 'gamma': 'auto', 'kernel': 'linear'},
  {'C': 30, 'gamma': 'scale', 'kernel': 'rbf'},
  {'C': 30, 'gamma': 'scale', 'kernel': 'linear'},
  {'C': 30, 'gamma': 'auto', 'kernel': 'rbf'},
  {'C': 30, 'gamma': 'auto', 'kernel': 'linear'}],
 'split0_test_score': array([0.9       , 0.96666667, 0.9       , 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 1.        ,
        0.96666667, 1.        , 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([0.93333333, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ]),
 'split2_test_score': array([0.9       , 0.96666667, 0.93333333, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.9       ,
        0.96666667, 0.9       , 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.93333333, 0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 0.93333333,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.93333333, 0.96666667,
        0.93333333, 0.96666667, 0.9       , 0.93333333, 0.9       ]),
 'split4_test_score': array([0.9, 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. ,
        1. , 1. , 1. , 1. , 1. , 1. , 1. ]),
 'mean_test_score': array([0.92      , 0.97333333, 0.94666667, 0.97333333, 0.96666667,
        0.98      , 0.98      , 0.98      , 0.98      , 0.97333333,
        0.98      , 0.97333333, 0.98      , 0.96666667, 0.96666667,
        0.96666667, 0.97333333, 0.96      , 0.96      , 0.96      ]),
 'std_test_score': array([0.02666667, 0.01333333, 0.03399346, 0.01333333, 0.02108185,
        0.01632993, 0.01632993, 0.01632993, 0.01632993, 0.03887301,
        0.01632993, 0.03887301, 0.01632993, 0.0421637 , 0.03651484,
        0.0421637 , 0.02494438, 0.04898979, 0.03887301, 0.04898979]),
 'rank_test_score': array([20,  7, 19,  7, 13,  1,  1,  1,  1,  7,  1,  7,  1, 13, 12, 13,  7,
        16, 16, 16], dtype=int32)}

In [45]:
results = pd.DataFrame(classifiers.cv_results_)
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.006071,0.001236,0.003999,0.000383,0.1,scale,rbf,"{'C': 0.1, 'gamma': 'scale', 'kernel': 'rbf'}",0.900000,0.933333,0.900000,0.966667,0.9,0.920000,0.026667,20
1,0.003965,0.000784,0.003875,0.001100,0.1,scale,linear,"{'C': 0.1, 'gamma': 'scale', 'kernel': 'linear'}",0.966667,0.966667,0.966667,0.966667,1.0,0.973333,0.013333,7
2,0.012043,0.012245,0.005240,0.001575,0.1,auto,rbf,"{'C': 0.1, 'gamma': 'auto', 'kernel': 'rbf'}",0.900000,0.966667,0.933333,0.933333,1.0,0.946667,0.033993,19
3,0.004994,0.000793,0.004508,0.000874,0.1,auto,linear,"{'C': 0.1, 'gamma': 'auto', 'kernel': 'linear'}",0.966667,0.966667,0.966667,0.966667,1.0,0.973333,0.013333,7
4,0.005121,0.000845,0.005324,0.002137,1.0,scale,rbf,"{'C': 1, 'gamma': 'scale', 'kernel': 'rbf'}",0.966667,0.966667,0.966667,0.933333,1.0,0.966667,0.021082,13
5,0.005019,0.001299,0.005015,0.003058,1.0,scale,linear,"{'C': 1, 'gamma': 'scale', 'kernel': 'linear'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
6,0.004618,0.001467,0.003452,0.000822,1.0,auto,rbf,"{'C': 1, 'gamma': 'auto', 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
7,0.002913,0.000505,0.002434,0.000691,1.0,auto,linear,"{'C': 1, 'gamma': 'auto', 'kernel': 'linear'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
8,0.003039,0.000710,0.002083,0.000398,10.0,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
9,0.003718,0.000434,0.003301,0.001275,10.0,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.966667,1.0,0.973333,0.038873,7
10,0.005272,0.001842,0.002971,0.000852,10.0,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
11,0.003666,0.001021,0.002820,0.000607,10.0,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.966667,1.0,0.973333,0.038873,7
12,0.003225,0.000819,0.001937,0.000379,20.0,scale,rbf,"{'C': 20, 'gamma': 'scale', 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
13,0.002628,0.000575,0.002515,0.000905,20.0,scale,linear,"{'C': 20, 'gamma': 'scale', 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,13
14,0.002835,0.000784,0.002317,0.000769,20.0,auto,rbf,"{'C': 20, 'gamma': 'auto', 'kernel': 'rbf'}",0.966667,1.000000,0.900000,0.966667,1.0,0.966667,0.036515,12
15,0.002576,0.000825,0.001719,0.000374,20.0,auto,linear,"{'C': 20, 'gamma': 'auto', 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,13
16,0.002462,0.000436,0.001771,0.000290,30.0,scale,rbf,"{'C': 30, 'gamma': 'scale', 'kernel': 'rbf'}",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,7
17,0.002549,0.000544,0.001894,0.000452,30.0,scale,linear,"{'C': 30, 'gamma': 'scale', 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.900000,1.0,0.960000,0.048990,16
18,0.003536,0.000381,0.002607,0.000593,30.0,auto,rbf,"{'C': 30, 'gamma': 'auto', 'kernel': 'rbf'}",0.966667,1.000000,0.900000,0.933333,1.0,0.960000,0.038873,16
19,0.002547,0.000865,0.001772,0.000536,30.0,auto,linear,"{'C': 30, 'gamma': 'auto', 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.900000,1.0,0.960000,0.048990,16

In [46]:
results[['param_C', 'param_kernel', 'param_gamma', 'mean_test_score']]

    param_C param_kernel param_gamma  mean_test_score
0       0.1          rbf       scale         0.920000
1       0.1       linear       scale         0.973333
2       0.1          rbf        auto         0.946667
3       0.1       linear        auto         0.973333
4       1.0          rbf       scale         0.966667
5       1.0       linear       scale         0.980000
6       1.0          rbf        auto         0.980000
7       1.0       linear        auto         0.980000
8      10.0          rbf       scale         0.980000
9      10.0       linear       scale         0.973333
10     10.0          rbf        auto         0.980000
11     10.0       linear        auto         0.973333
12     20.0          rbf       scale         0.980000
13     20.0       linear       scale         0.966667
14     20.0          rbf        auto         0.966667
15     20.0       linear        auto         0.966667
16     30.0          rbf       scale         0.973333
17     30.0       linear       scale         0.960000
18     30.0          rbf        auto         0.960000
19     30.0       linear        auto         0.960000

Random search CV